parser: babel-eslint
plugins:
  - babel
env:
  browser: true
  es6: true
  commonjs: true
extends: eslint:recommended
parserOptions:
  sourceType: module
  ecmaFeatures:
    - impliedStrict
    - experimentalObjectRestSpread
globals:
  $: true
rules:
  object-shorthand: 1
  no-cond-assign: 1
  indent:
    - 2
    - 2
  quotes:
    - 1
    - single
  semi:
    - 2
    - always
  comma-dangle:
    - 2
    - always-multiline
  no-unused-vars: 1
  no-console: 0
