<nav class="nav">
  <div class="row"><div class="columns nav__container">
    <ol class="nav__container-item">
      <li><a href="/" class="nav__logo">同济大学开源镜像</a></li>
    </ol>
    <ol class="nav__container-item">
      <li><a href="/" class="nav__item{% if page.layout == 'index' %} active{% endif %}">镜像列表</a></li>
      <li><a href="/status" class="nav__item">服务状态</a></li>
      <li><a href="/help" class="nav__item">使用帮助</a></li>
    </ol>
  </div></div>
</nav>
